# sudo: required
dist: bionic # (18.04)

language: cpp
compiler:
  - clang

addons:
  apt:
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
    packages:
      - libace-6.4.5
      - libace-dev
      - boost1.67
      - libssl-dev
      - libmysqlclient-dev
      - libreadline6-dev
      - zlib1g-dev
      - libbz2-dev
      - g++-6

services:
  - mysql

git:
  depth: 10

before_install:
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init

install:
  # - mysql -uroot -e 'create database test_mysql;'
  - mkdir build
  - cd build
  - cmake ../ -DNOJEM=0 -DCMAKE_INSTALL_PREFIX=check_install -DWITH_DYNAMIC_LINKING=1
  - cd ..
  
script:
  - $CXX --version
  # - mysql -uroot < sql/create/create_mysql.sql
  # - mysql -utrinity -ptrinity auth < sql/base/auth_database.sql
  # - ./contrib/check_updates.sh auth 3.3.5 auth localhost
  # - mysql -utrinity -ptrinity characters < sql/base/characters_database.sql
  # - ./contrib/check_updates.sh characters 3.3.5 characters localhost
  # - mysql -utrinity -ptrinity world < sql/base/dev/world_database.sql
  # - cat sql/updates/world/3.3.5/*.sql | mysql -utrinity -ptrinity world
  # - mysql -uroot < sql/create/drop_mysql.sql
  - cd build
  - make -j 4 -k && make install
  - cd check_install/bin
  # - ./authserver --version
  # - ./worldserver --version